application: main
version: 1
runtime: python
api_version: 1

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /media
  static_dir: media

- url: /appengine_admin_media
  static_dir: appengine_admin/media
  secure: never

- url: /.*
  script: main.py

